### PR TITLE
UF-283: Upgrade uberfire-tutorial to Java 8 and Errai UI

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by ederign** [comment]
@paulovmr ping when you make the changes ok?

**Comment by paulovmr** [comment]
@ederign All done!

**Comment by ederign** [comment]
+1 @thanks paulo (I've already tested locally)
Related PRs: 
uberfire/uberfire#312
https://github.com/uberfire/uberfire-tutorial/pull/7

**Comment by csadilek** [comment]
master: 7340bf2713da3c38795d713ed2c5d49e1f06d6d6

**Pull request closed without merging**
